### ISSUE TITLE
zh-cn-about.json is missing

### ISSUE THREAD

**Issue by LitoMore** [ceasbz/mzsi-cli#2]
mzsi-cli version: 1.2.0
mzsi version: 1.3.0

## Expected behavior

```bash
$ mzsi 10 12 zh-cn
天秤
```

## Actual behavior

```bash
$ mzsi 10 12 zh-cn
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/mzsi-cli/node_modules/mzsi/i18n/zh-cn-about.json'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at module.exports (/usr/local/lib/node_modules/mzsi-cli/node_modules/mzsi/index.js:96:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/mzsi-cli/cli.js:51:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
```

## How to reproduce

```bash
$ mzsi 10 12 zh-cn
```

You missed `zh-cn-about.json` when [mzsi](https://github.com/ceasbz/mzsi)'s `npm publish`. :]

**Comment by ceasbz** [comment]
D:

**Comment by ceasbz** [comment]
Ty @LitoMore

**Comment by ceasbz** [comment]
@LitoMore Could you update the CLI and test again?

**Comment by LitoMore** [comment]
Cool!

![](http://photo1.fanfou.com/v1/mss_3d027b52ec5a4d589e68050845611e68/ff/n0/0e/6a/as_211008.jpg)
